use std::{env, fs, path::PathBuf};

include!("keystream.rs");

fn main() {
    emit_updater_token();
    tauri_build::build()
}

/// Bake the updater's GitHub token into the binary, obfuscated.
///
/// MultiZone's source repository is private, so release assets are not publicly
/// downloadable and the updater has to authenticate. The token is read from the
/// environment at compile time — never committed, never present in the working
/// tree — and written out as an obfuscated byte array (see `keystream.rs` for
/// what that does and does not protect against).
///
/// Absent env var is not an error: local dev builds and anyone building from a
/// checkout get a binary with no token, where update checks simply fail with the
/// "no manifest found" message the UI already handles. Only release CI supplies
/// one.
fn emit_updater_token() {
    println!("cargo:rerun-if-env-changed=MULTIZONE_UPDATER_TOKEN");

    let token = env::var("MULTIZONE_UPDATER_TOKEN").unwrap_or_default();
    let token = token.trim();

    let obfuscated: Vec<u8> = token
        .bytes()
        .zip(token_keystream(token.len()))
        .map(|(byte, key)| byte ^ key)
        .collect();

    let body = format!(
        "// @generated by build.rs — do not edit.\n\
         pub(super) const OBFUSCATED_UPDATER_TOKEN: &[u8] = &{obfuscated:?};\n"
    );

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR always set by cargo"))
        .join("updater_token.rs");
    fs::write(&out, body).expect("failed to write generated updater token");

    if token.is_empty() {
        println!(
            "cargo:warning=MULTIZONE_UPDATER_TOKEN not set — this build cannot check for updates."
        );
    }
}
