import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { Copy, Check, Table2, BarChart3 } from "lucide-react";
import {
  type ChartData,
  type ChartTheme,
  formatValue,
  readChartTheme,
  renderChartSvg,
} from "@/lib/chart";
import { CHROME_QUIET } from "@/lib/chrome";

/**
 * The active chart palette, kept current.
 *
 * The theme is applied as inline custom properties on `<html>` (see the app
 * store's `applyTheme`) and the mode as a class on the same element, so one
 * observer over both attributes catches a mode switch, an accent change and a
 * repainted background alike — which is the difference between a chart that is
 * theme-aware and one that was theme-aware when it was first drawn.
 */
export function useChartTheme(): ChartTheme {
  const [theme, setTheme] = useState<ChartTheme>(() => readChartTheme());
  useEffect(() => {
    const obs = new MutationObserver(() => setTheme(readChartTheme()));
    obs.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "style"],
    });
    return () => obs.disconnect();
  }, []);
  return theme;
}

/** The chart's own width, so it fills the message column rather than guessing at it. */
function useMeasuredWidth(fallback: number): [React.RefObject<HTMLDivElement | null>, number] {
  const ref = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(fallback);
  useLayoutEffect(() => {
    const el = ref.current;
    if (!el) return;
    const apply = () => {
      const w = el.clientWidth;
      if (w > 0) setWidth(Math.round(w));
    };
    apply();
    const obs = new ResizeObserver(apply);
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return [ref, width];
}

/** Column-major view of the chart's own numbers, for the data table behind it. */
function chartAsTable(data: ChartData): { headers: string[]; rows: string[][] } {
  const headers = ["", ...data.series.map((s) => s.name)];
  const rows = data.labels.map((label, i) => [
    label,
    ...data.series.map((s) => {
      const v = s.values[i];
      return v === null || v === undefined ? "" : formatValue(v, data.unit);
    }),
  ]);
  return { headers, rows };
}

export function ChartBlock({ data, caption }: { data: ChartData; caption?: string }) {
  const theme = useChartTheme();
  const [ref, width] = useMeasuredWidth(600);
  const [showData, setShowData] = useState(false);
  const [copied, setCopied] = useState(false);

  // Horizontal bars grow downward with their categories; everything else keeps
  // a fixed plot so a chart does not change shape as its series are read.
  const plotHeight =
    data.type === "bar" && data.horizontal
      ? Math.max(180, Math.min(560, data.labels.length * 34 + 60))
      : 300;

  // One id namespace per block: two charts in one answer both define
  // `tex-1`, and duplicate ids in a document resolve to whichever came first.
  const idPrefix = useMemo(() => `mzc${Math.random().toString(36).slice(2, 8)}`, []);

  const svg = useMemo(
    () =>
      renderChartSvg(data, theme, {
        width: Math.max(280, width),
        height: plotHeight,
        idPrefix,
      }),
    [data, theme, width, plotHeight, idPrefix],
  );

  const table = useMemo(() => chartAsTable(data), [data]);

  async function onCopy() {
    const tsv = [table.headers, ...table.rows].map((r) => r.join("\t")).join("\n");
    await navigator.clipboard.writeText(tsv);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="my-2 overflow-hidden rounded-md border border-[var(--color-border)] bg-[var(--color-panel)]">
      <div ref={ref} className="w-full px-2 pt-2">
        {/* Generated by `renderChartSvg` from data this app already holds; every
            piece of user or model text in it is escaped on the way in. */}
        <div className="w-full" dangerouslySetInnerHTML={{ __html: svg }} />
      </div>

      {caption && (
        <div className="px-3 pb-1 text-center text-xs text-[var(--color-text-muted)]">{caption}</div>
      )}

      <div className="flex items-center justify-end gap-1 border-t border-[var(--color-border)] px-2 py-1 text-xs text-[var(--color-text-muted)]">
        <button
          onClick={() => setShowData((v) => !v)}
          className={`flex items-center gap-1 rounded px-1.5 py-0.5 ${CHROME_QUIET}`}
        >
          {showData ? <BarChart3 size={12} /> : <Table2 size={12} />}
          {showData ? "hide data" : "data"}
        </button>
        <button onClick={onCopy} className={`flex items-center gap-1 rounded px-1.5 py-0.5 ${CHROME_QUIET}`}>
          {copied ? <Check size={12} /> : <Copy size={12} />}
          {copied ? "copied" : "copy"}
        </button>
      </div>

      {showData && (
        <div className="max-h-72 overflow-auto border-t border-[var(--color-border)]">
          <table className="w-full text-xs">
            <thead className="sticky top-0 bg-[var(--color-panel)]">
              <tr>
                {table.headers.map((h, i) => (
                  <th
                    key={i}
                    className="border-b border-[var(--color-border)] px-2 py-1 text-left font-medium text-[var(--color-text-muted)]"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {table.rows.map((row, i) => (
                <tr key={i}>
                  {row.map((cell, j) => (
                    <td
                      key={j}
                      className={`border-b border-[var(--color-border)] px-2 py-1 ${
                        j === 0 ? "text-[var(--color-text-muted)]" : "tabular-nums"
                      }`}
                    >
                      {cell}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

/** The error state for a call that named a chart but gave nothing chartable. */
export function ChartError({ message }: { message: string }) {
  return (
    <div className="my-2 rounded border border-[var(--color-danger)] bg-[var(--color-panel)] p-3 text-xs">
      <div className="mb-1 text-[var(--color-danger)]">Chart error:</div>
      <pre className="whitespace-pre-wrap">{message}</pre>
    </div>
  );
}
